import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { AppBg } from "@/components/AppBg/AppBg";
import Layout from "@/layouts/Layout";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Exercise Test App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AppBg>
            <Layout>{children}</Layout>
          </AppBg>
        </Providers>
      </body>
    </html>
  );
}
